### ISSUE TITLE
Game abandoned because of Camera problems ? 

### ISSUE THREAD

**Issue by Sygmei** [opiter09/Murder-on-the-Cusp-of-an-Icsmaun-Sunset#1]
Is this game abandoned because of the camera problem ?

**Comment by opiter09** [comment]
What? No! Please don't take this personally! I just got kind of burned out on the whole thing.

**Comment by Sygmei** [comment]
Okay :)
Thanks a lot for all the time you spent on this game, your insight helped me a lot to improve some areas of the engine ! 
Don't hesitate to ping me on Discord if you have some time, I'd love to get some feedback ! 

Have a great day !
